### ISSUE TITLE
Rake Task

### ISSUE THREAD

**Issue by jchai002** [nyc-fireflies-2015/mojoe#357]
Hey Leah, can you configure the heroku environment and have a rake task ping the dyno every hour? This way there won't be any down time and if employers visit the site, there won't be a 20 second lag time.

**Comment by jchai002** [comment]
example 
under app/lib/tasks
make a file called ping.rake

inside paste these lines 

require 'net/http'

namespace :ping do
  desc "Ping our heroku dyno every 10, 60 or 3600 min"
  task :start do
    puts "Making the attempt to ping the dyno"

```
if ENV['URL']
  puts "Sending ping"

  uri = URI(ENV['URL'])
  Net::HTTP.get_response(uri)

  puts "success..."
end
```

  end
end

**Comment by leahgoldberg** [comment]
Hey,

I can look into it. I think there may be some restrictions around doing this -- Heroku may make us upgrade to more dynos, but I can give it a shot!

**Comment by sgharms** [comment]
This autoping thing generally works.  PEACE!

HARMS OUT.

**Comment by leahgoldberg** [comment]
Cool, thanks @sgharms !

**Comment by leahgoldberg** [comment]
So turns out that Heroku announced in July that they'll begin charging if your app is alive for more than 18 hours per day (https://blog.heroku.com/archives/2015/5/7/heroku-free-dynos)...

I'll look into having rake tasks run only during certain hours of the day. @jchai002 feel free to look into it too

**Comment by leahgoldberg** [comment]
Alright, done with a cron job!
